/**
 * Glyphs the harness set does not carry. Generated by extract.mjs; do not
 * edit this file. Attribution is in NOTICE.
 *
 * @module extracted
 */

/** The generator's input set. */
export const EXTRACTED_SET = 'lucide-static'

/** The generator's input version of lucide-static. */
export const EXTRACTED_FROM = '1.34.0'

/** The set, by this deployment's name for each glyph. */
export const extracted = Object.freeze({
  'terminal': {
    from: 'terminal',
    viewBox: '0 0 24 24',
    paths: [
      'M12 19h8',
      'm4 17 6-6-6-6',
    ],
    stroke: { width: 2, linecap: 'round', linejoin: 'round' },
  },
  'shrink': {
    from: 'minimize-2',
    viewBox: '0 0 24 24',
    paths: [
      'm14 10 7-7',
      'M20 10h-6V4',
      'm3 21 7-7',
      'M4 14h6v6',
    ],
    stroke: { width: 2, linecap: 'round', linejoin: 'round' },
  },
  'file': {
    from: 'file',
    viewBox: '0 0 24 24',
    paths: [
      'M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1-2 2z',
      'M14 2v5a1 1 0 0 0 1 1h5',
    ],
    stroke: { width: 2, linecap: 'round', linejoin: 'round' },
  },
  'copy-text': {
    from: 'files',
    viewBox: '0 0 24 24',
    paths: [
      'M15 2h-4a2 2 0 0 0-2 2v11a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V8',
      'M16.706 2.706A2.4 2.4 0 0 0 15 2v5a1 1 0 0 0 1 1h5a2.4 2.4 0 0 0-.706-1.706z',
      'M5 7a2 2 0 0 0-2 2v11a2 2 0 0 0 2 2h8a2 2 0 0 0 1.732-1',
    ],
    stroke: { width: 2, linecap: 'round', linejoin: 'round' },
  },
  'image': {
    from: 'image',
    viewBox: '0 0 24 24',
    paths: [
      'M5 3h14a2 2 0 0 1 2 2v14a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-14a2 2 0 0 1 2 -2z',
      'M7 9a2 2 0 1 0 4 0a2 2 0 1 0 -4 0',
      'm21 15-3.086-3.086a2 2 0 0 0-2.828 0L6 21',
    ],
    stroke: { width: 2, linecap: 'round', linejoin: 'round' },
  },
  'markdown': {
    from: 'file-text',
    viewBox: '0 0 24 24',
    paths: [
      'M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1-2 2z',
      'M14 2v5a1 1 0 0 0 1 1h5',
      'M10 9H8',
      'M16 13H8',
      'M16 17H8',
    ],
    stroke: { width: 2, linecap: 'round', linejoin: 'round' },
  },
  'signout': {
    from: 'log-out',
    viewBox: '0 0 24 24',
    paths: [
      'm16 17 5-5-5-5',
      'M21 12H9',
      'M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4',
    ],
    stroke: { width: 2, linecap: 'round', linejoin: 'round' },
  },
  'shield': {
    from: 'shield',
    viewBox: '0 0 24 24',
    paths: [
      'M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z',
    ],
    stroke: { width: 2, linecap: 'round', linejoin: 'round' },
  },
  'list': {
    from: 'list',
    viewBox: '0 0 24 24',
    paths: [
      'M3 5h.01',
      'M3 12h.01',
      'M3 19h.01',
      'M8 5h13',
      'M8 12h13',
      'M8 19h13',
    ],
    stroke: { width: 2, linecap: 'round', linejoin: 'round' },
  },
  'brush': {
    from: 'brush',
    viewBox: '0 0 24 24',
    paths: [
      'm11 10 3 3',
      'M6.5 21A3.5 3.5 0 1 0 3 17.5a2.62 2.62 0 0 1-.708 1.792A1 1 0 0 0 3 21z',
      'M9.969 17.031 21.378 5.624a1 1 0 0 0-3.002-3.002L6.967 14.031',
    ],
    stroke: { width: 2, linecap: 'round', linejoin: 'round' },
  },
  'sandbox': {
    from: 'box',
    viewBox: '0 0 24 24',
    paths: [
      'M21 8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16Z',
      'm3.3 7 8.7 5 8.7-5',
      'M12 22V12',
    ],
    stroke: { width: 2, linecap: 'round', linejoin: 'round' },
  },
  'window': {
    from: 'app-window',
    viewBox: '0 0 24 24',
    paths: [
      'M4 4h16a2 2 0 0 1 2 2v12a2 2 0 0 1 -2 2h-16a2 2 0 0 1 -2 -2v-12a2 2 0 0 1 2 -2z',
      'M10 4v4',
      'M2 8h20',
      'M6 4v4',
    ],
    stroke: { width: 2, linecap: 'round', linejoin: 'round' },
  },
  'people': {
    from: 'users',
    viewBox: '0 0 24 24',
    paths: [
      'M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2',
      'M16 3.128a4 4 0 0 1 0 7.744',
      'M22 21v-2a4 4 0 0 0-3-3.87',
      'M5 7a4 4 0 1 0 8 0a4 4 0 1 0 -8 0',
    ],
    stroke: { width: 2, linecap: 'round', linejoin: 'round' },
  },
  'ticket': {
    from: 'ticket',
    viewBox: '0 0 24 24',
    paths: [
      'M2 9a3 3 0 0 1 0 6v2a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2v-2a3 3 0 0 1 0-6V7a2 2 0 0 0-2-2H4a2 2 0 0 0-2 2Z',
      'M13 5v2',
      'M13 17v2',
      'M13 11v2',
    ],
    stroke: { width: 2, linecap: 'round', linejoin: 'round' },
  },
  'history': {
    from: 'history',
    viewBox: '0 0 24 24',
    paths: [
      'M3 12a9 9 0 1 0 9-9 9.75 9.75 0 0 0-6.74 2.74L3 8',
      'M3 3v5h5',
      'M12 7v5l4 2',
    ],
    stroke: { width: 2, linecap: 'round', linejoin: 'round' },
  },
  'settings': {
    from: 'settings',
    viewBox: '0 0 24 24',
    paths: [
      'M9.671 4.136a2.34 2.34 0 0 1 4.659 0 2.34 2.34 0 0 0 3.319 1.915 2.34 2.34 0 0 1 2.33 4.033 2.34 2.34 0 0 0 0 3.831 2.34 2.34 0 0 1-2.33 4.033 2.34 2.34 0 0 0-3.319 1.915 2.34 2.34 0 0 1-4.659 0 2.34 2.34 0 0 0-3.32-1.915 2.34 2.34 0 0 1-2.33-4.033 2.34 2.34 0 0 0 0-3.831A2.34 2.34 0 0 1 6.35 6.051a2.34 2.34 0 0 0 3.319-1.915',
      'M9 12a3 3 0 1 0 6 0a3 3 0 1 0 -6 0',
    ],
    stroke: { width: 2, linecap: 'round', linejoin: 'round' },
  },
  'panel': {
    from: 'panel-left',
    viewBox: '0 0 24 24',
    paths: [
      'M5 3h14a2 2 0 0 1 2 2v14a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-14a2 2 0 0 1 2 -2z',
      'M9 3v18',
    ],
    stroke: { width: 2, linecap: 'round', linejoin: 'round' },
  },
  'code': {
    from: 'file-code',
    viewBox: '0 0 24 24',
    paths: [
      'M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1-2 2z',
      'M14 2v5a1 1 0 0 0 1 1h5',
      'M10 12.5 8 15l2 2.5',
      'm14 12.5 2 2.5-2 2.5',
    ],
    stroke: { width: 2, linecap: 'round', linejoin: 'round' },
  },
  'data': {
    from: 'file-braces',
    viewBox: '0 0 24 24',
    paths: [
      'M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1-2 2z',
      'M14 2v5a1 1 0 0 0 1 1h5',
      'M10 12a1 1 0 0 0-1 1v1a1 1 0 0 1-1 1 1 1 0 0 1 1 1v1a1 1 0 0 0 1 1',
      'M14 18a1 1 0 0 0 1-1v-1a1 1 0 0 1 1-1 1 1 0 0 1-1-1v-1a1 1 0 0 0-1-1',
    ],
    stroke: { width: 2, linecap: 'round', linejoin: 'round' },
  },
  'archive': {
    from: 'file-archive',
    viewBox: '0 0 24 24',
    paths: [
      'M13.659 22H18a2 2 0 0 0 2-2V8a2.4 2.4 0 0 0-.706-1.706l-3.588-3.588A2.4 2.4 0 0 0 14 2H6a2 2 0 0 0-2 2v11.5',
      'M14 2v5a1 1 0 0 0 1 1h5',
      'M8 12v-1',
      'M8 18v-2',
      'M8 7V6',
      'M6 20a2 2 0 1 0 4 0a2 2 0 1 0 -4 0',
    ],
    stroke: { width: 2, linecap: 'round', linejoin: 'round' },
  },
  'table': {
    from: 'file-spreadsheet',
    viewBox: '0 0 24 24',
    paths: [
      'M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1-2 2z',
      'M14 2v5a1 1 0 0 0 1 1h5',
      'M8 13h2',
      'M14 13h2',
      'M8 17h2',
      'M14 17h2',
    ],
    stroke: { width: 2, linecap: 'round', linejoin: 'round' },
  },
  'media': {
    from: 'file-video',
    viewBox: '0 0 24 24',
    paths: [
      'M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1-2 2z',
      'M14 2v5a1 1 0 0 0 1 1h5',
      'M15.033 13.44a.647.647 0 0 1 0 1.12l-4.065 2.352a.645.645 0 0 1-.968-.56v-4.704a.645.645 0 0 1 .967-.56z',
    ],
    stroke: { width: 2, linecap: 'round', linejoin: 'round' },
  },
})
