/**
 * Who is allowed into the operator's console.
 *
 * Not a tenant. That distinction is the whole reason this service exists
 * separately: an administrator is a different kind of principal from somebody
 * who signed up, and running both through one session made the console a page
 * on the tenant surface that happened to answer 404 to everyone else. Hiding
 * is not isolating.
 *
 * So: a username and a password, checked here, with a session that belongs to
 * this deployment and no other. No email, no code, no account row — none of
 * which an operator should need, and all of which would tie this service back
 * to the one it was moved out of.
 *
 * ## The password is not the boundary
 *
 * One credential opens everything here: every account, every tier, the model
 * credential every tenant's agent calls with. A password is a lock on a door,
 * and this door should not be on a public street. The deployment is expected
 * to publish this service to an internal network, and the compose file binds
 * it to loopback by default for that reason.
 *
 * What this file can do, it does: the password is stored as a hash and never
 * in the clear, comparison is constant-time, attempts are rate-limited per
 * address, and a deployment that configured no hash refuses to start rather
 * than starting with a default. A default password is a published password.
 *
 * @module auth
 */

import { randomBytes, scrypt, timingSafeEqual } from 'node:crypto'
import process from 'node:process'
import { promisify } from 'node:util'

const scryptAsync = promisify(scrypt)

/** Who to let in. One operator, because a shared console needs no directory. */
export const USERNAME = process.env.ADMIN_USERNAME ?? 'admin'

/**
 * The password, as `scrypt$<salt-hex>$<hash-hex>`.
 *
 * Generated by `node admin/hash-password.mjs`, which is the only supported way
 * to produce one: a hash somebody pasted from elsewhere may use parameters
 * this cannot read, and the failure would be a console nobody can enter.
 */
const CREDENTIAL = process.env.ADMIN_PASSWORD_HASH ?? ''

/** scrypt's cost, fixed here so a stored hash never has to carry it. */
const KEY_LENGTH = 64

/** How many attempts one address gets, and over what window. */
const ATTEMPTS = 8
const WINDOW_MS = 10 * 60 * 1000

/** @type {Map<string, number[]>} */
const attempts = new Map()

/**
 * Whether this deployment can admit anybody at all.
 *
 * Checked at startup so a console with no credential says so on the console
 * rather than at the moment somebody tries to sign in.
 *
 * @returns {boolean} whether a credential is configured.
 */
export function canSignIn() {
  return /^scrypt\$[0-9a-f]+\$[0-9a-f]+$/.test(CREDENTIAL)
}

/**
 * Turn a password into something safe to store.
 *
 * @param {string} password - the password to hash.
 * @returns {Promise<string>} the stored form.
 */
export async function hashPassword(password) {
  const salt = randomBytes(16)
  const derived = await scryptAsync(password, salt, KEY_LENGTH)
  return `scrypt$${salt.toString('hex')}$${Buffer.from(derived).toString('hex')}`
}

/**
 * Whether these are the operator's credentials.
 *
 * Both halves are compared even when the username is already wrong, so the
 * time this takes says nothing about which half failed.
 *
 * @param {string} username - what was typed.
 * @param {string} password - likewise.
 * @returns {Promise<boolean>} whether to admit them.
 */
export async function verify(username, password) {
  if (!canSignIn()) return false
  const [, saltHex, hashHex] = CREDENTIAL.split('$')
  const derived = await scryptAsync(password, Buffer.from(saltHex, 'hex'), KEY_LENGTH)
  const stored = Buffer.from(hashHex, 'hex')
  const passwordMatches = derived.length === stored.length && timingSafeEqual(derived, stored)
  // `&` and not `&&`: the comparison above has already run, and short-
  // circuiting here would leak which half was wrong through timing.
  const nameMatches = username === USERNAME
  return Boolean(Number(passwordMatches) & Number(nameMatches))
}

/**
 * Whether this address may try again.
 *
 * Counted per address rather than per username, because there is one username
 * and rate-limiting it would lock the operator out from anywhere the moment
 * anyone guessed at them.
 *
 * @param {string} address - the caller.
 * @returns {boolean} whether to let them try.
 */
export function mayAttempt(address) {
  const now = Date.now()
  const recent = (attempts.get(address) ?? []).filter((at) => at > now - WINDOW_MS)
  attempts.set(address, recent)
  return recent.length < ATTEMPTS
}

/**
 * Record one failed attempt.
 * @param {string} address - the caller.
 * @returns {void}
 */
export function failed(address) {
  const now = Date.now()
  attempts.set(address, [...(attempts.get(address) ?? []).filter((at) => at > now - WINDOW_MS), now])
}

/**
 * Forget an address's failures, once it has succeeded.
 * @param {string} address - the caller.
 * @returns {void}
 */
export function succeeded(address) {
  attempts.delete(address)
}
